export const people = [
  {
    id: 1,
    name: 'Leslie Alexander',
    phone: '1-493-747-9031',
    email: 'lesliealexander@example.com',
    role: 'Co-Founder / CEO',
    url: 'https://example.com',
    profileUrl: '#',
    imageUrl: 'https://i.pravatar.cc/150?img=1',
  },
  {
    id: 2,
    name: 'Miles Ferguson',
    phone: '1-555-314-1592',
    email: 'milesferguson@example.com',
    role: 'CTO',
    url: 'https://example.com',
    profileUrl: '#',
    imageUrl: 'https://i.pravatar.cc/150?img=2',
  },
  {
    id: 3,
    name: 'Laura Thompson',
    phone: '1-587-835-9421',
    email: 'laurathompson@example.com',
    role: 'CFO',
    url: 'https://example.com',
    profileUrl: '#',
    imageUrl: 'https://i.pravatar.cc/150?img=3',
  },
  {
    id: 4,
    name: 'Sean Cooper',
    phone: '1-724-888-1234',
    email: 'seancooper@example.com',
    role: 'COO',
    url: 'https://example.com',
    profileUrl: '#',
    imageUrl: 'https://i.pravatar.cc/150?img=4',
  },
  {
    id: 5,
    name: 'Samantha Peters',
    phone: '1-678-543-9801',
    email: 'samanthapeters@example.com',
    role: 'VP of Marketing',
    url: 'https://example.com',
    profileUrl: '#',
    imageUrl: 'https://i.pravatar.cc/150?img=5',
  },
];

export const recent = [people[5], people[4], people[2], people[10], people[16]];
